version: '3'

services:
  # proxy:
  #   image: slowmike/michael_proxy_v1
  #   depends_on:
  #     # - similar_products
  #     - photo_gallery
  #     # - product_info
  #     # - reviews
  #   ports:
  #     - '80:3000'

  # similar_products:
  #   image: hanjoon3/similar-products_similarproducts:component
  #   depends_on:
  #     - similar_products_db
  #   ports:
  #     - '3001:3001'
  # similar_products_db:
  #   image: hanjoon3/similar-products_database:database

  photo_gallery:
    image: slowmike/photo_gallery_server_v1
    depends_on:
      - photo_gallery_db
    ports:
      - '3002:3002'
  photo_gallery_db:
    image: slowmike/photo_gallery_db_v1

  # product_info:
  #   image: tonykijak/viamis:v0.1
  #   depends_on:
  #     - product_info_db
  #   ports:
  #     - '3003:3003'
  
  # product_info_db:
  #   image: tonykijak/viamis:db_v0.1

  # reviews:
  #   image: cheyennenoel/review-server
  #   depends_on:
  #     - reviews_db
  #   ports:
  #     - '3004:3004'
  
  # reviews_db:
  #   image: cheyennenoel/review-database
  
  proxy:
    build: ./
    volumes:
      - ./:/src/app
    depends_on:
      # - similar_products
      - photo_gallery
      # - product_info
      # - reviews
    ports:
      - '3000:3000'
  
